name: strawberry
version: '0.5.3+git'
summary: music player and collection organizer
description: |
  Strawberry is a music player and collection organizer.
  It is a fork of Clementine released in 2018 aimed at music collectors,
  audio enthusiasts and audiophiles

grade: stable
confinement: strict

parts:
  strawberry:
    plugin: cmake
    source-type: git
    source: https://github.com/jonaski/strawberry
    after: [desktop-qt5]
    override-build: |
      cmake ../src -DCMAKE_INSTALL_PREFIX=/usr
      make -j $(getconf _NPROCESSORS_ONLN)
      make DESTDIR=$SNAPCRAFT_PART_INSTALL install
      sed -i 's|Icon=strawberry|Icon=/usr/share/icons/hicolor/128x128/apps/strawberry\.png|' $SNAPCRAFT_PART_INSTALL/usr/share/applications/org.strawbs.strawberry.desktop
      sed -i 's|TryExec=.*|TryExec=/snap/bin/strawberry|' $SNAPCRAFT_PART_INSTALL/usr/share/applications/org.strawbs.strawberry.desktop

    build-packages:
      - cmake
      - make
      - gcc
      - g++
      - protobuf-compiler
      - libglib2.0-dev
      - libdbus-1-dev
      - libprotobuf-dev
      - libboost-dev
      - libsqlite3-dev
      - libasound2-dev
      - libpulse-dev
      - libtag1-dev
      - qtbase5-dev
      - qtbase5-dev-tools
      - qtbase5-private-dev
      - libqt5x11extras5-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libxine2-dev
      - libvlc-dev
      - libcdio-dev
      - libgpod-dev
      - libimobiledevice-dev
      - libmtp-dev
      - libplist-dev
      - libusbmuxd-dev
      - libchromaprint-dev

    stage-packages:
      - libstdc++6
      - libgcc1
      - libprotobuf9v5
      - libpcre16-3
      - libqt5core5a
      - libqt5gui5
      - libqt5widgets5
      - libqt5concurrent5
      - libqt5network5
      - libqt5dbus5
      - libqt5sql5
      - libqt5x11extras5
      - libqt5sql5-sqlite
      - libsqlite3-0
      - libgpm2
      - libasound2
      - libpulse0
      - libcdio13
      - libgpod4
      - libmtp9
      - libimobiledevice6
      - libplist3
      - libusbmuxd4
      - libxine2
      - libvlc5
      - libvlccore8
      - libtag1v5
      - libchromaprint0
      - zlib1g
      - libx11-6
      - libdb5.3
      - dbus-x11
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0
      - gstreamer1.0-alsa
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-libav
      - oxygen-icon-theme
      - breeze-icon-theme

apps:
  strawberry:
    command: desktop-launch $SNAP/usr/bin/strawberry
    desktop: usr/share/applications/org.strawbs.strawberry.desktop
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
    plugs:
      - system-observe
      - system-trace
      - system-files
      - home
      - dbus
      - udisks2
      - network
      - network-control
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - alsa
      - pulseaudio
      - mount-observe
      - fuse-support
      - removable-media
      - optical-drive
      - raw-usb
      - media-hub
      - screen-inhibit-control
      - unity7
    slots:
      - mpris
      - network-bind
